
[[constraint]]
  name = "github.com/Clever/analytics-util"
  version = "1.2.0"

[[constraint]]
  name = "github.com/Clever/discovery-go"

[[constraint]]
  name = "github.com/Clever/pathio"

[[constraint]]
  name = "github.com/Clever/pq"

[[constraint]]
  name = "github.com/DATA-DOG/go-sqlmock"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.0"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"

[[constraint]]
  name = "github.com/kardianos/osext"

[[constraint]]
  name = "github.com/segmentio/go-env"

[[constraint]]
  name = "github.com/stretchr/testify"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "6.24.0"

[[constraint]]
  name = "gopkg.in/yaml.v2"
